config/routes.rb
Clouddevelopmentresearch::Application.routes.draw do
  
  resources :accounts
  get "accounts/index"

  get "accounts/new"

  get "accounts/search"
  match "/accounts/:id", to: "accounts#show", as: "account"

  get "accounts/create"

  get "accounts/show"
  
  get "accounts/edit"
  
  root :to => "accounts#index"
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  include Databasedotcom::Rails::Controller

  def index
    @accounts = Merchandise__c.all
    
    config = YAML.load_file(File.join(::Rails.root, 'config', 'databasedotcom.yml'))
    puts "-------------------------------------------------------------------------------------"
    puts config["username"]
    puts config["password"]
    puts "======================================================================================"
  end

  def new
    config = YAML.load_file(File.join(::Rails.root, 'config', 'databasedotcom.yml'))
    client = Databasedotcom::Client.new(config)          
    client.authenticate :username => config[:username], :password => config[:password]
    puts "--------------------------------------------------------------------------------"
    puts client.materialize("Merchandise__c")
    puts "================================================================================"

    parentId = client.query("select ParentId from account where name like 'First Account'")
    
    @account = Merchandise__c.new
  end

  def search
    config = YAML.load_file(File.join(::Rails.root, 'config', 'databasedotcom.yml'))
    client = Databasedotcom::Client.new(config)          
    client.authenticate :username => config[:username], :password => config[:password]
    @accounts = client.query("select id, name from merchandise where name like 'jet%'")
  end

  def create
    Merchandise__c.create Merchandise__c.coerce_params(params[:account])
    redirect_to accounts_path
  end

  def show
    @account = Merchandise__c.find(params[:id])
  end
  
  def edit
  
    @account = Merchandise__c.find(params[:id])
    puts "EDITBEGIN++++++++++++++++++++++++++++++++++++++++++++++++++"
    puts @account
    puts "EDITEND++++++++++++++++++++++++++++++++++++++++++++++++++++"
    
  end

  def update
    @account = Merchandise__c.find(params[:id])
    @account.update_attributes(params[:user])
    render "show"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

app/views/accounts/edit.html.erb
<h1>Editing user  <%= @account.Name %> </h1>

<%= @account["Description__c"] %>

<span class="nav"><a href="/accounts/index">Search</a></span><p/>
<span class="title">Edit Account</span>
<p/>

<form method="post" action="/accounts/<%= params[:id]%>/save"> 
<table border="0" cellspacing="1" cellpadding="5" bgcolor="#CCCCCC">
	<tr bgcolor="#407BA8">
		<td style="color: #ffffff; font-weight: bold;">Name</td>
		<td bgcolor="#ffffff"><%= @account["Name"] %></td>
	</tr>
	<tr bgcolor="#407BA8">
		<td style="color: #ffffff; font-weight: bold;">City</td>
		<td bgcolor="#ffffff"><input type="input" name="Description__c" value="<%= @account["Description__c"] %>" style="width:150px"></td>
	</tr>

		<td colspan="2" bgcolor="#ffffff" align="center"><input type="submit" value="Submit"></td> 
	</tr>	
</table>

app/views/accounts/index.html.erb
<ul>
	<% @accounts.each do |account| %>
	<li><%= link_to account.Name, account_path(account.Id) %></li>
	<% end %>
</ul>

<%= link_to "create a new account", new_account_path %>

app/views/accounts/new.html.erb
<%= form_for(@account) do |form| %>
    <% Merchandise__c.attributes.select {|a| Merchandise__c.updateable?(a)}.each do |attr| %>
        <field>
            <%= form.label attr, Merchandise__c.label_for(attr) %>
            <% case Merchandise__c.field_type(attr) %>
                <% when "boolean" %>
                    <%= form.check_box attr %>
                <% when "multipicklist" %>
                <% when "picklist" %>
                    <% puts "Rendering picklist for #{attr}, value is #{@account[attr]}, type is #{Merchandise__c.field_type(attr)}"%>
                    <%= form.select attr, Merchandise__c.picklist_values(attr).collect {|p| [p["label"], p["value"]]}, :multiple => (Merchandise__c.field_type(attr) == "multipicklist") %>
                <% else %>
                    <%= form.text_field attr%>
            <% end %>
        </field>
        <br>
    <% end %>
    <%= form.submit %>
<% end %>

app/views/accounts/search.html.erb
	<% @accounts.each do |account| %>
	<li><%= link_to account.Name, account_path(account.Id) %></li>
	<% end %>

app/views/accounts/show.html.erb
<h1><%= @account.Name %></h1>


<table border="0" cellspacing="1" cellpadding="5" bgcolor="#CCCCCC">
	<tr bgcolor="#407BA8">
		<td style="color: #ffffff; font-weight: bold;">Name</td>
		<td bgcolor="#ffffff"><%= @account["Name"] %></td>
	</tr>
	<tr bgcolor="#407BA8">
		<td style="color: #ffffff; font-weight: bold;">Description</td>
		<td bgcolor="#ffffff"><%= @account["Description__c"] %></td>
	</tr>
	<tr bgcolor="#407BA8">
		<td style="color: #ffffff; font-weight: bold;">Price</td>
		<td bgcolor="#ffffff"><%= @account["Price__c"] %></td>
	</tr>
	<tr bgcolor="#407BA8">
		<td style="color: #ffffff; font-weight: bold;">Total Inventory</td>
		<td bgcolor="#ffffff"><%= @account["Total_Inventory__c"] %></td>
	</tr>

</table>

<%= link_to "edit account", edit_account_path %>
  
  <%= link_to 'Edit', edit_account_path(@account) %> |
  <%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clouddevelopmentresearch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>